name: release
on:
  push:
    branches:
    tags: 'v*'

jobs:
  release:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: olegtarasov/get-tag@v2.1.3
        id: tag

      - name: Install dependencies
        uses: amitie10g/install-package@v1.2.5
        with:
          apt: build-essential nasm gcc-multilib g++-multilib cmake xorriso dosfstools mtools unzip wget

      - name: Build towboot image
        run: HHUOS_REDISTRIBUTABLE_BUILD=1 ./build.sh --target towboot --type Default

      - name: Build limine image
        run: HHUOS_REDISTRIBUTABLE_BUILD=1 ./build.sh --target limine --type Default

      - name: Download licenses
        run: mkdir -p license && cp LICENSE license/hhuOS.txt &&
          wget -O license/Limine.txt https://raw.githubusercontent.com/limine-bootloader/limine/trunk/COPYING &&
          wget -O license/FatFs.txt https://raw.githubusercontent.com/hhuOS/FatFs/master/LICENSE &&
          wget -O license/doomgeneric.txt https://raw.githubusercontent.com/hhuOS/doomgeneric/master/LICENSE &&
          wget -O license/quakegeneric.txt https://raw.githubusercontent.com/hhuOS/quakegeneric/master/LICENSE &&
          wget -O license/tinygl.txt https://raw.githubusercontent.com/C-Chads/tinygl/main/LICENSE

      - name: Create artifact
        run: mkdir -p hhuOS-${{ steps.commit.outputs.short }} && cp -r hhuOS-limine.iso hhuOS-towboot.img hdd0.img floppy0.img run.sh README.md license hhuOS-${{ steps.commit.outputs.short }}

      - name: Publish Release
        uses: softprops/action-gh-release@v1
        with:
          files: hhuOS-${{ steps.tag.outputs.tag }}.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.PUBLISH_TOKEN }}